## 一、张量数据结构
张量的数据类型和numpy.array基本一一对应，但是不支持str类型。

包括:

torch.float64(torch.double),

torch.float32(torch.float),

torch.float16,

torch.int64(torch.long),

torch.int32(torch.int),

torch.int16,

torch.int8,

torch.uint8,

torch.bool

一般神经网络建模使用的都是torch.float32(torch.float)类型。

In [1]:
import numpy as np
import torch

In [2]:
# 自动判断类型

t1 = torch.tensor(1); print(t1, t1.dtype)
t2 = torch.tensor(2.0); print(t2, t2.dtype)
t3 = torch.tensor(True); print(t3, t3.dtype)

tensor(1) torch.int64
tensor(2.) torch.float32
tensor(True) torch.bool


In [3]:
# 指定数据类型

t4 = torch.tensor(1, dtype = torch.int32); print(t4, t4.dtype)
t5 = torch.tensor(2.0, dtype = torch.double); print(t5, t5.dtype)

tensor(1, dtype=torch.int32) torch.int32
tensor(2., dtype=torch.float64) torch.float64


In [4]:
# 使用特定类型构造函数

t6 = torch.IntTensor(1); print(t6, t6.dtype, t6.type())
t7 = torch.Tensor(np.array(2.0)); print(t7, t7.dtype, t7.type()) 
# torch.tensor根据data自动判断类型；torch.Tensor生成固定类型的FloatTensor

t8 = torch.BoolTensor(np.array([1, 0, 2, 0])); print(t8, t8.dtype, t8.type())

tensor([1828150782], dtype=torch.int32) torch.int32 torch.IntTensor
tensor(2.) torch.float32 torch.FloatTensor
tensor([ True, False,  True, False]) torch.bool torch.BoolTensor


In [5]:
# 不同类型转换

t9 = torch.tensor(1); print(t9, t9.dtype)
x = t9.float(); print(x, x.dtype) # 调用float方法转换成浮点类型
y = t9.type(torch.float); print(y, y.dtype) #使用type函数转换成浮点类型
z = t9.type_as(x); print(z, z.dtype) #使用type_as方法转换成某个tensor相同的类型

tensor(1) torch.int64
tensor(1.) torch.float32
tensor(1.) torch.float32
tensor(1.) torch.float32


## 二、张量的维度
不同类型的数据可以用不同维度(dimension)的张量来表示。

标量为0维张量，向量为1维张量，矩阵为2维张量。

彩色图像有rgb三个通道，可以表示为3维张量。

视频还有时间维，可以表示为4维张量。

可以简单地总结为：有几层中括号，就是多少维的张量。

In [6]:
scalar = torch.tensor(True)
print(scalar)
print(scalar.dim()) # 标量，0维张量
print(scalar.shape)

tensor(True)
0
torch.Size([])


In [7]:
vector = torch.tensor([1.0, 2.0, 3.0, 4.0]) #向量，1维张量
print(vector)
print(vector.dim())
print(vector.shape)

tensor([1., 2., 3., 4.])
1
torch.Size([4])


In [8]:
matrix = torch.tensor([[1.0, 2.0], 
                       [3.0, 4.0]]) #矩阵, 2维张量
print(matrix)
print(matrix.dim())
print(matrix.shape)

tensor([[1., 2.],
        [3., 4.]])
2
torch.Size([2, 2])


In [9]:
tensor3 = torch.tensor([[[1.0, 2.0], [3.0, 4.0]], [[5.0, 6.0], [7.0, 8.0]]])  # 3维张量
tensor3_1 = torch.rand(3, 2, 2)

print(tensor3)
print(tensor3.dim())
print(tensor3.shape) # 理解为2个2*2矩阵拼接成一个3维张量
print('\n')
print(tensor3_1)
print(tensor3_1.dim())
print(tensor3_1.shape) # 理解为3个2*2矩阵拼接成一个3维张量

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])
3
torch.Size([2, 2, 2])


tensor([[[0.1577, 0.4496],
         [0.7152, 0.1112]],

        [[0.4229, 0.9447],
         [0.7538, 0.2481]],

        [[0.5383, 0.9819],
         [0.3493, 0.4386]]])
3
torch.Size([3, 2, 2])


In [10]:
tensor4 = torch.tensor([[[[1.0, 1.0], [2.0,2.0]], [[3.0, 3.0], [4.0, 4.0]]],
                        [[[5.0, 5.0], [6.0,6.0]], [[7.0, 7.0], [8.0, 8.0]]]])  # 4维张量
print(tensor4)
print(tensor4.dim())
print(tensor4.shape)

tensor([[[[1., 1.],
          [2., 2.]],

         [[3., 3.],
          [4., 4.]]],


        [[[5., 5.],
          [6., 6.]],

         [[7., 7.],
          [8., 8.]]]])
4
torch.Size([2, 2, 2, 2])


## 三、张量的尺寸
shape属性查看张量的尺寸

size()方法查看张量在每一维的长度

使用view方法改变张量的尺寸。如果view方法改变尺寸失败，可以使用reshape方法。

In [11]:
scalar = torch.tensor(True)
print(scalar.size())
print(scalar.shape)

torch.Size([])
torch.Size([])


In [12]:
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])
print(vector.size())
print(vector.shape)

torch.Size([4])
torch.Size([4])


In [13]:
matrix = torch.tensor([[1.0,2.0],[3.0,4.0]])
print(matrix.size())
print(matrix.shape)

torch.Size([2, 2])
torch.Size([2, 2])


In [14]:
tensor3 = torch.rand(3, 2, 2)  # 3维张量
print(tensor3)
print(tensor3.shape)
print(tensor3.size())
print(tensor3.size(0))
print(tensor3.size(1))
print(tensor3.size(2))

tensor([[[0.2440, 0.5094],
         [0.6609, 0.2784]],

        [[0.3684, 0.6799],
         [0.9825, 0.8350]],

        [[0.1412, 0.7738],
         [0.0751, 0.8754]]])
torch.Size([3, 2, 2])
torch.Size([3, 2, 2])
3
2
2


In [15]:
# 使用view可以改变张量尺寸

vector = torch.arange(0, 12)
print(vector)
print(vector.shape)

matrix34 = vector.view(3, 4)
print(matrix34)
print(matrix34.shape)

matrix43 = vector.view(4, -1) #-1表示该位置长度由程序自动推断
print(matrix43)
print(matrix43.shape)

matrix232 = vector.view(2, 3, -1)
print(matrix232)
print(matrix232.shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
torch.Size([4, 3])
tensor([[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]])
torch.Size([2, 3, 2])


In [16]:
# 有些操作会让张量存储结构扭曲，直接使用view会失败，可以用reshape方法

matrix26 = torch.arange(0, 12).view(2, 6)
print(matrix26)
print(matrix26.shape)

# 转置操作让张量存储结构扭曲
matrix62 = matrix26.t()
print(matrix62)
print(matrix62.is_contiguous())

# 直接使用view方法会失败，可以使用reshape方法
# matrix34 = matrix62.view(3, 4) #error!
matrix34 = matrix62.reshape(3, 4) #等价于matrix34 = matrix62.contiguous().view(3,4)
print(matrix34)

# print(matrix62.view(3, 4))# error!

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])
torch.Size([2, 6])
tensor([[ 0,  6],
        [ 1,  7],
        [ 2,  8],
        [ 3,  9],
        [ 4, 10],
        [ 5, 11]])
False
tensor([[ 0,  6,  1,  7],
        [ 2,  8,  3,  9],
        [ 4, 10,  5, 11]])


## 四、张量和numpy数组
可以用numpy方法从Tensor得到numpy数组，也可以用torch.from_numpy从numpy数组得到Tensor。

这两种方法关联的Tensor和numpy数组是共享数据内存的。

如果改变其中一个，另外一个的值也会发生改变。

如果有需要，可以用张量的clone方法拷贝张量，中断这种关联。

此外，还可以使用item方法从标量张量得到对应的Python数值。

使用tolist方法从张量得到对应的Python数值列表。

In [17]:
# 从numpy数组得到tensor：torch.from_numpy

arr = np.zeros(3)
tensor = torch.from_numpy(arr)
print('before add 1:')
print(arr)
print(tensor)

print('\nafter add 1:')
np.add(arr, 1, out = arr) # arr和tensor共享内存，改变一方另一方也改变
print(arr)
print(tensor)

before add 1:
[0. 0. 0.]
tensor([0., 0., 0.], dtype=torch.float64)

after add 1:
[1. 1. 1.]
tensor([1., 1., 1.], dtype=torch.float64)


In [18]:
# 从tensor得到numpy数组：numpy()

tensor = torch.zeros(3)
arr = tensor.numpy()
print('before add 1:')
print(tensor)
print(arr)

print('\nafter add 1:')

tensor.add_(1) # 使用带下划线的方法表示计算结果会返回给调用张量
# 等价于 torch.add(tensor, 1, out = tensor)
print(tensor)
print(arr)

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[1. 1. 1.]


In [19]:
# 要中断这种关联，使用clone()方法

tensor = torch.zeros(3)

# 使用clone方法拷贝张量, 拷贝后的张量和原始张量内存独立

print('before add 1:')
arr = tensor.clone().numpy()
print(tensor)
print(arr)

print('\nafter add 1:')
torch.add(tensor, 1, out = tensor)
print(tensor)
print(arr)

before add 1:
tensor([0., 0., 0.])
[0. 0. 0.]

after add 1:
tensor([1., 1., 1.])
[0. 0. 0.]


In [20]:
# item方法和tolist方法可以将张量转换成Python数值和数值列表

scalar = torch.tensor(1.0)
s = scalar.item()
print(s)
print(type(s))

print('\n')

tensor = torch.rand(2, 2)
t = tensor.tolist()
print(tensor)
print(t)
print(type(t))

1.0
<class 'float'>


tensor([[0.8363, 0.8089],
        [0.2180, 0.3343]])
[[0.8362599015235901, 0.8089374303817749], [0.21795809268951416, 0.3342616558074951]]
<class 'list'>
