# 0-2 张量的结构操作
张量的操作主要包括张量的结构操作和张量的数学运算。

张量结构操作诸如：张量创建，索引切片，维度变换，合并分割。

张量数学运算主要有：标量运算，向量运算，矩阵运算。张量的运算采用广播机制

## 一、创建张量

In [1]:
import numpy as np
import torch

In [2]:
a = torch.tensor([1, 2, 3], dtype = torch.float)
print(a)

tensor([1., 2., 3.])


In [3]:
b = torch.arange(1, 10, step = 2)
print(b)
print(b.dtype)

tensor([1, 3, 5, 7, 9])
torch.int64


In [4]:
# 线性间距向量
# torch.linspace(start, end, steps=100, out=None) → Tensor 
# 返回一个1维张量，包含在区间start和end上均匀间隔的step个点。输出张量的长度由steps决定。

c = torch.linspace(0, 10, steps = 4)
print(c)

tensor([ 0.0000,  3.3333,  6.6667, 10.0000])


In [5]:
d = torch.zeros(3, 3)
print(d)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [6]:
a = torch.ones((3, 3), dtype = torch.int)
b = torch.zeros_like(a, dtype = torch.float)
print(a)
print(b)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [7]:
torch.fill_(b, 6)
print(b)

tensor([[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]])


In [8]:
# 均匀分布
# torch.rand 从区间[0, 1)的均匀分布中抽取的一组随机数。

torch.manual_seed(0)
minval, maxval = 0, 10
rand = torch.rand([5])
a = minval + (maxval - minval)*rand
print(rand)
print(a)

tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
tensor([4.9626, 7.6822, 0.8848, 1.3203, 3.0742])


In [9]:
# 标准正态分布
# torch.randn(*sizes, out=None) → Tensor 
# 返回一个张量，包含了从标准正态分布(均值为0，方差为 1，即高斯白噪声)中抽取一组随机数

torch.manual_seed(0)
print(torch.randn(3, 2))

tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]])


In [10]:
# 正态分布随机
# torch.normal(means, std, out=None) 
# 返回一个张量，包含从给定参数means,std的离散正态分布中抽取随机数。 
# 均值means是一个张量，包含每个输出元素相关的正态分布的均值。 std是一个张量，包含每个输出元素相关的正态分布的标准差。

torch.manual_seed(0)
b = torch.normal(mean = torch.zeros(3, 2), std = torch.ones(3, 2)) # mean = 0, std = 1, 即标准正态分布
print(b)

tensor([[ 1.5410, -0.2934],
        [-2.1788,  0.5684],
        [-1.0845, -1.3986]])


In [11]:
# 正态分布随机

torch.manual_seed(0)
mean, std = 2, 5
randn = torch.randn((3, 3))
c = std * randn + mean 
print(randn)
print(c)

tensor([[ 1.5410, -0.2934, -2.1788],
        [ 0.5684, -1.0845, -1.3986],
        [ 0.4033,  0.8380, -0.7193]])
tensor([[ 9.7050,  0.5329, -8.8939],
        [ 4.8422, -3.4226, -4.9930],
        [ 4.0167,  6.1901, -1.5963]])


In [12]:
# 上面c等价于c_1

torch.manual_seed(0)
mean = torch.fill_(torch.zeros((3, 3)), 2)
std = torch.fill_(torch.zeros((3, 3)), 5)
c_1 = torch.normal(mean = mean, std = std)
print(c_1)

tensor([[ 9.7050,  0.5329, -8.8939],
        [ 4.8422, -3.4226, -4.9930],
        [ 4.0167,  6.1901, -1.5963]])


In [13]:
# 整数随机排列
# torch.randperm(n, out=None) → LongTensor
# 给定参数n，返回一个从0到n-1的随机整数排列。参数n：int，上边界（不包含）

d = torch.randperm(20)
print(d)

tensor([ 6, 19,  1,  8, 12, 16,  7,  9, 17, 18, 11, 10, 15,  0,  4, 14, 13,  2,
         3,  5])


In [14]:
# 特殊矩阵

# 单位阵
I = torch.eye(3, 3)
print(I)

# 对角阵
t = torch.diag(torch.tensor([1, 2, 3]))
print(t)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[1, 0, 0],
        [0, 2, 0],
        [0, 0, 3]])


## 二、索引切片
张量的索引切片方式和numpy几乎是一样的。切片时支持缺省参数和省略号。

可以通过索引和切片对部分元素进行修改。

此外，对于不规则的切片提取,可以使用torch.index_select, torch.masked_select, torch.take

如果要通过修改张量的某些元素得到新的张量，可以使用torch.where, torch.masked_fill, torch.index_fill

In [15]:
# 均匀分布

torch.manual_seed(0)
minval, maxval = 0, 10
rand = torch.rand(5, 5)
input_tensor = minval + (maxval - minval)*rand
t = torch.floor(input_tensor).int()

print(rand)
print(input_tensor)
print(t)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074],
        [0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939],
        [0.5185, 0.6977, 0.8000, 0.1610, 0.2823],
        [0.6816, 0.9152, 0.3971, 0.8742, 0.4194]])
tensor([[4.9626, 7.6822, 0.8848, 1.3203, 3.0742],
        [6.3408, 4.9009, 8.9644, 4.5563, 6.3231],
        [3.4889, 4.0172, 0.2233, 1.6886, 2.9389],
        [5.1852, 6.9767, 8.0001, 1.6103, 2.8227],
        [6.8161, 9.1519, 3.9710, 8.7416, 4.1941]])
tensor([[4, 7, 0, 1, 3],
        [6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2],
        [6, 9, 3, 8, 4]], dtype=torch.int32)


In [16]:
# 第0行
print(t[0])

# 倒数第一行
print(t[-1])

tensor([4, 7, 0, 1, 3], dtype=torch.int32)
tensor([6, 9, 3, 8, 4], dtype=torch.int32)


In [17]:
# 第1行第3列
print(t[1, 3])
print(t[1][3])

tensor(4, dtype=torch.int32)
tensor(4, dtype=torch.int32)


In [18]:
# 第1行至第3行
print(t[1:4, :])

tensor([[6, 4, 8, 4, 6],
        [3, 4, 0, 1, 2],
        [5, 6, 8, 1, 2]], dtype=torch.int32)


In [19]:
# 第1行至第3行，第0列到第3列一列每隔两列取一列
print(t[1:4, :4:2])

tensor([[6, 8],
        [3, 0],
        [5, 8]], dtype=torch.int32)


In [20]:
#可以使用索引和切片修改部分元素
x = torch.tensor([[1, 2], [3, 4]], dtype = torch.float32, requires_grad=True)
x.data[1, :] = torch.tensor([0.0, 0.0])
x

tensor([[1., 2.],
        [0., 0.]], requires_grad=True)

In [21]:
a = torch.arange(27).view(3, 3, 3)
print(a)

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]]])


In [22]:
# 省略号可以表示多个冒号
print(a[..., 1])

tensor([[ 1,  4,  7],
        [10, 13, 16],
        [19, 22, 25]])


### 关于tensor dim
dim意为 只有dim指定的维度可变，其他都是不变的

In [23]:
# torch.argmax(input, dim=None, keepdim=False)返回指定维度最大值的序号

torch.manual_seed(0)

a = torch.rand((4, 3))
print(a)

b = torch.argmax(a, dim = 0) # 只有dim0可变，dim1不变 -> dim1去比较
print(b)

c = torch.argmax(a, dim = 1) # 只有dim1可变，dim0不变 -> dim0去比较
print(c)

tensor([[0.4963, 0.7682, 0.0885],
        [0.1320, 0.3074, 0.6341],
        [0.4901, 0.8964, 0.4556],
        [0.6323, 0.3489, 0.4017]])
tensor([3, 2, 1])
tensor([1, 2, 1, 0])


In [24]:
t = torch.arange(0, 6).view(2, 3)
print(t)

print('t.sum():', t.sum())
print('t.sum(dim = 0):', t.sum(dim = 0)) # 只有dim0可变，dim1不变，对dim1操作 = [3, 5, 7]
print('t.sum(dim = 1):', t.sum(dim = 1)) # 只有dim1可变，dim0不变，对dim0操作 = [3, 12]

tensor([[0, 1, 2],
        [3, 4, 5]])
t.sum(): tensor(15)
t.sum(dim = 0): tensor([3, 5, 7])
t.sum(dim = 1): tensor([ 3, 12])


In [25]:
# torch.cumsum(input, dim, out=None) → Tensor
# 返回输入沿指定维度的累积和。例如，如果输入是一个N元向量，则结果也是一个N元向量，第i个输出元素值为 yi=x1+x2+x3+...+xi

t = torch.arange(0, 6).view(2, 3)
print(t)
print(t.cumsum(dim = 0)) # 沿dim1操作：0,3 1,5 2,7
print(t.cumsum(dim = 1)) # 沿dim0操作：0,1,3 3,7,12

tensor([[0, 1, 2],
        [3, 4, 5]])
tensor([[0, 1, 2],
        [3, 5, 7]])
tensor([[ 0,  1,  3],
        [ 3,  7, 12]])


考虑班级成绩册的例子，有4个班级，每个班级10个学生，每个学生7门科目成绩。可以用一个4×10×7的张量来表示。

In [26]:
minval = 0
maxval = 100
scores = torch.floor(minval + (maxval - minval) * torch.rand([4, 10, 7])).int()
print(scores)

tensor([[[ 2, 16, 29, 51, 69, 80, 16],
         [28, 68, 91, 39, 87, 41, 55],
         [95,  3, 18, 37, 30, 93, 17],
         [26, 15,  3, 20, 92, 72, 74],
         [52, 24, 58,  3, 13, 24, 81],
         [79, 27, 48, 81, 99, 69, 56],
         [83, 20, 59, 11, 15, 24, 72],
         [70, 20, 65, 77, 43, 51, 61],
         [81, 98, 11, 31, 69, 91, 93],
         [94, 59,  6, 54, 18,  3, 94]],

        [[88,  0, 59, 41, 41, 27, 69],
         [20, 68, 75, 85, 68,  0, 17],
         [74, 60, 10, 21, 97, 83, 28],
         [37,  2, 49, 12, 11, 47, 57],
         [29, 79, 19, 95, 84,  7, 37],
         [52, 57, 61, 69, 52, 25, 73],
         [ 2, 20, 37, 25, 32,  9, 39],
         [60, 17, 47, 85, 44, 51, 45],
         [60, 81, 97, 81, 97, 46,  5],
         [26, 84, 49, 25, 11,  3,  7]],

        [[39, 77, 77,  1, 81, 10, 39],
         [29, 40, 40,  5,  6, 42, 50],
         [27, 68,  4, 46, 93, 29, 95],
         [68,  4, 81, 44, 27, 89,  9],
         [55, 39, 85, 63, 74, 67, 37],
         [39,  8, 77,

In [27]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的全部成绩

torch.index_select(scores, dim = 1, index = torch.tensor([0, 5, 9]))

tensor([[[ 2, 16, 29, 51, 69, 80, 16],
         [79, 27, 48, 81, 99, 69, 56],
         [94, 59,  6, 54, 18,  3, 94]],

        [[88,  0, 59, 41, 41, 27, 69],
         [52, 57, 61, 69, 52, 25, 73],
         [26, 84, 49, 25, 11,  3,  7]],

        [[39, 77, 77,  1, 81, 10, 39],
         [39,  8, 77, 89, 84, 14, 52],
         [56, 10, 23, 90,  9, 46, 99]],

        [[68, 51,  6, 74, 14, 35, 33],
         [72, 25, 16, 21, 78, 76, 88],
         [91, 33, 64, 38, 47, 19, 66]]], dtype=torch.int32)

In [28]:
# 抽取每个班级第0个学生，第5个学生，第9个学生的第1门课程，第3门课程，第6门课程成绩

q = torch.index_select(
    torch.index_select(scores, dim = 1, index = torch.tensor([0, 5, 9])), 
    dim = 2, index = torch.tensor([1, 3, 6])
)
print(q)

tensor([[[16, 51, 16],
         [27, 81, 56],
         [59, 54, 94]],

        [[ 0, 41, 69],
         [57, 69, 73],
         [84, 25,  7]],

        [[77,  1, 39],
         [ 8, 89, 52],
         [10, 90, 99]],

        [[51, 74, 33],
         [25, 21, 88],
         [33, 38, 66]]], dtype=torch.int32)


In [29]:
# 抽取第0个班级第0个学生的第0门课程，第2个班级的第4个学生的第1门课程，第3个班级的第9个学生第6门课程成绩
# take将输入看成一维数组，输出和index同形状

s = torch.take(scores, torch.tensor([0*10*7+0, 2*10*7+4*7+1, 3*10*7+9*7+6]))
print(s)

tensor([ 2, 39, 66], dtype=torch.int32)


In [30]:
# 抽取分数大于等于80分的分数（布尔索引）
# 结果是1维张量

g = torch.masked_select(scores, scores >= 80)
print(g)

tensor([80, 91, 87, 95, 93, 92, 81, 81, 99, 83, 81, 98, 91, 93, 94, 94, 88, 85,
        97, 83, 95, 84, 85, 81, 97, 81, 97, 84, 81, 93, 95, 81, 89, 85, 89, 84,
        82, 84, 92, 90, 99, 91, 94, 80, 87, 86, 91, 88, 91, 93, 89, 91],
       dtype=torch.int32)


以上这些方法仅能提取张量的部分元素值，但不能更改张量的部分元素值得到新的张量。

如果要通过修改张量的部分元素值得到新的张量，可以使用torch.where, torch.index_fill 和 torch.masked_fill

torch.where可以理解为if的张量版本。

torch.index_fill的选取元素逻辑和torch.index_select相同。

torch.masked_fill的选取元素逻辑和torch.masked_select相同。

In [31]:
# 如果分数大于60分，赋值成1，否则赋值成0
ifpass = torch.where(scores > 60, torch.tensor(1), torch.tensor(0))
print(ifpass)

tensor([[[0, 0, 0, 0, 1, 1, 0],
         [0, 1, 1, 0, 1, 0, 0],
         [1, 0, 0, 0, 0, 1, 0],
         [0, 0, 0, 0, 1, 1, 1],
         [0, 0, 0, 0, 0, 0, 1],
         [1, 0, 0, 1, 1, 1, 0],
         [1, 0, 0, 0, 0, 0, 1],
         [1, 0, 1, 1, 0, 0, 1],
         [1, 1, 0, 0, 1, 1, 1],
         [1, 0, 0, 0, 0, 0, 1]],

        [[1, 0, 0, 0, 0, 0, 1],
         [0, 1, 1, 1, 1, 0, 0],
         [1, 0, 0, 0, 1, 1, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 1, 1, 0, 0],
         [0, 0, 1, 1, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [0, 1, 1, 1, 1, 0, 0],
         [0, 1, 0, 0, 0, 0, 0]],

        [[0, 1, 1, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 1, 0, 1],
         [1, 0, 1, 0, 0, 1, 0],
         [0, 0, 1, 1, 1, 1, 0],
         [0, 0, 1, 1, 1, 0, 0],
         [0, 0, 0, 1, 0, 0, 0],
         [1, 0, 0, 0, 1, 0, 1],
         [1, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 1, 0, 0, 1]],

        [[1, 0, 0, 1, 0, 0, 0],
  

In [32]:
#将每个班级第0个学生，第5个学生，第9个学生的全部成绩赋值成满分

torch.index_fill(scores, dim = 1, index = torch.tensor([0, 5, 9]), value = 100)
# 等价于scores.index_fill(dim = 1, index = torch.tensor([0, 5, 9]), value = 100)


tensor([[[100, 100, 100, 100, 100, 100, 100],
         [ 28,  68,  91,  39,  87,  41,  55],
         [ 95,   3,  18,  37,  30,  93,  17],
         [ 26,  15,   3,  20,  92,  72,  74],
         [ 52,  24,  58,   3,  13,  24,  81],
         [100, 100, 100, 100, 100, 100, 100],
         [ 83,  20,  59,  11,  15,  24,  72],
         [ 70,  20,  65,  77,  43,  51,  61],
         [ 81,  98,  11,  31,  69,  91,  93],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [ 20,  68,  75,  85,  68,   0,  17],
         [ 74,  60,  10,  21,  97,  83,  28],
         [ 37,   2,  49,  12,  11,  47,  57],
         [ 29,  79,  19,  95,  84,   7,  37],
         [100, 100, 100, 100, 100, 100, 100],
         [  2,  20,  37,  25,  32,   9,  39],
         [ 60,  17,  47,  85,  44,  51,  45],
         [ 60,  81,  97,  81,  97,  46,   5],
         [100, 100, 100, 100, 100, 100, 100]],

        [[100, 100, 100, 100, 100, 100, 100],
         [ 29,  40,  40,   5, 

In [33]:
# 将分数小于60分的分数赋值成60分
b = torch.masked_fill(scores, scores < 60, 60)
# 等价于b = scores.masked_fill(scores < 60, 60)
print(b)

tensor([[[60, 60, 60, 60, 69, 80, 60],
         [60, 68, 91, 60, 87, 60, 60],
         [95, 60, 60, 60, 60, 93, 60],
         [60, 60, 60, 60, 92, 72, 74],
         [60, 60, 60, 60, 60, 60, 81],
         [79, 60, 60, 81, 99, 69, 60],
         [83, 60, 60, 60, 60, 60, 72],
         [70, 60, 65, 77, 60, 60, 61],
         [81, 98, 60, 60, 69, 91, 93],
         [94, 60, 60, 60, 60, 60, 94]],

        [[88, 60, 60, 60, 60, 60, 69],
         [60, 68, 75, 85, 68, 60, 60],
         [74, 60, 60, 60, 97, 83, 60],
         [60, 60, 60, 60, 60, 60, 60],
         [60, 79, 60, 95, 84, 60, 60],
         [60, 60, 61, 69, 60, 60, 73],
         [60, 60, 60, 60, 60, 60, 60],
         [60, 60, 60, 85, 60, 60, 60],
         [60, 81, 97, 81, 97, 60, 60],
         [60, 84, 60, 60, 60, 60, 60]],

        [[60, 77, 77, 60, 81, 60, 60],
         [60, 60, 60, 60, 60, 60, 60],
         [60, 68, 60, 60, 93, 60, 95],
         [68, 60, 81, 60, 60, 89, 60],
         [60, 60, 85, 63, 74, 67, 60],
         [60, 60, 77,

## 三、维度变换
维度变换相关函数主要有 torch.reshape(或者调用张量的view方法), torch.squeeze, torch.unsqueeze, torch.transpose

torch.reshape 可以改变张量的形状。

torch.squeeze 可以减少维度。

torch.unsqueeze 可以增加维度。

torch.transpose 可以交换维度。

In [34]:
# 张量的view方法有时候会调用失败，可以使用reshape方法。

torch.manual_seed(0)
minval, maxval = 0, 255
a = (minval + (maxval - minval) * torch.rand([1, 3, 3, 2])).int()
print(a.shape)
print(a)

torch.Size([1, 3, 3, 2])
tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


In [35]:
# 改成 （3,6）形状的张量

b_1 = a.view([3, 6])
print(b_1.shape)
print(b_1)

b_2 = a.reshape([3, 6])
print(b_2.shape)
print(b_2)

torch.Size([3, 6])
tensor([[126, 195,  22,  33,  78, 161],
        [124, 228, 116, 161,  88, 102],
        [  5,  43,  74, 132, 177, 204]], dtype=torch.int32)
torch.Size([3, 6])
tensor([[126, 195,  22,  33,  78, 161],
        [124, 228, 116, 161,  88, 102],
        [  5,  43,  74, 132, 177, 204]], dtype=torch.int32)


In [36]:
# 改回成 [1,3,3,2] 形状的张量

c = torch.reshape(b_1, [1, 3, 3, 2])
print(c.shape)
print(c)

torch.Size([1, 3, 3, 2])
tensor([[[[126, 195],
          [ 22,  33],
          [ 78, 161]],

         [[124, 228],
          [116, 161],
          [ 88, 102]],

         [[  5,  43],
          [ 74, 132],
          [177, 204]]]], dtype=torch.int32)


如果张量在某个维度上只有一个元素，利用torch.squeeze可以消除这个维度。

torch.unsqueeze的作用和torch.squeeze的作用相反。


In [37]:
a = torch.tensor([[1.0, 2.0]])
s = torch.squeeze(a)
print(a)
print(a.shape)

print(s)
print(s.shape)

tensor([[1., 2.]])
torch.Size([1, 2])
tensor([1., 2.])
torch.Size([2])


In [38]:
# 在第0维插入长度为1的一个维度
d_1 = torch.unsqueeze(s, axis = 0)  

# 在第1维插入长度为1的一个维度
d_2 = torch.unsqueeze(s, axis = 1)  

print(s)
print(s.shape)

print(d_1)
print(d_1.shape)

print(d_2)
print(d_2.shape)

tensor([1., 2.])
torch.Size([2])
tensor([[1., 2.]])
torch.Size([1, 2])
tensor([[1.],
        [2.]])
torch.Size([2, 1])


torch.transpose可以交换张量的维度，torch.transpose常用于图片存储格式的变换上。

如果是二维的矩阵，通常会调用矩阵的转置方法 matrix.t()，等价于 torch.transpose(matrix, 0, 1)。

In [39]:
minval=0
maxval=255

# Batch, Height, Width, Channel
data = torch.floor(minval + (maxval - minval) * torch.rand([100, 256, 256, 4])).int()
print(data.shape)

# 转换成 Pytorch默认的图片格式 Batch, Channel, Height, Width 
# 需要交换两次
data_t = torch.transpose(torch.transpose(data, 1, 2), 1, 3)
# 等价于data_t = torch.transpose(torch.transpose(data, 2, 3), 1, 2)，方法不唯一
print(data_t.shape)


torch.Size([100, 256, 256, 4])
torch.Size([100, 4, 256, 256])


In [40]:
matrix = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matrix)
print(matrix.t()) #等价于torch.transpose(matrix, 0, 1)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


## 四、合并分割
可以用torch.cat方法和torch.stack方法将多个张量合并，可以用torch.split方法把一个张量分割成多个张量。

torch.cat和torch.stack有略微的区别，torch.cat是连接，不会增加维度，而torch.stack是堆叠，会增加维度。

In [41]:
a = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
b = torch.tensor([[5.0, 6.0], [7.0, 8.0]])
c = torch.tensor([[9.0, 10.0], [11.0, 12.0]])

abc_cat = torch.cat([a, b, c], dim = 0)
print(abc_cat.shape)
print(abc_cat)

torch.Size([6, 2])
tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])


In [42]:
torch.cat([a, b, c], axis = 0) # torch中dim和axis参数名可以混用

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])

In [43]:
torch.cat([a, b, c], axis = 1)

tensor([[ 1.,  2.,  5.,  6.,  9., 10.],
        [ 3.,  4.,  7.,  8., 11., 12.]])

In [44]:
abc_stack = torch.stack([a, b, c], axis = 0) 
print(abc_stack.shape)
print(abc_stack)

torch.Size([3, 2, 2])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


In [45]:
torch.stack([a, b, c], axis = 1)

tensor([[[ 1.,  2.],
         [ 5.,  6.],
         [ 9., 10.]],

        [[ 3.,  4.],
         [ 7.,  8.],
         [11., 12.]]])

In [46]:
# torch.split是torch.cat的逆运算，可以指定分割份数平均分割，也可以通过指定每份的记录数量进行分割。
print(abc_cat)
a, b, c = torch.split(abc_cat, split_size_or_sections = 2, dim = 0) #每份2个进行分割
print(a)
print(b)
print(c)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[5., 6.],
        [7., 8.]])
tensor([[ 9., 10.],
        [11., 12.]])


In [47]:
print(abc_cat)
p, q, r = torch.split(abc_cat, split_size_or_sections =[4, 1, 1], dim = 0) # 每份分别为[4,1,1]
print(p)
print(q)
print(r)

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[ 9., 10.]])
tensor([[11., 12.]])
