# 0-3 张量的数学运算

张量的数学运算符可以分为标量运算符、向量运算符、以及矩阵运算符。

## 一、标量运算
加减乘除乘方，以及三角函数，指数，对数等常见函数，逻辑比较运算符等都是标量运算符。

标量运算符的特点是对张量实施逐元素运算。

有些标量运算符对常用的数学运算符进行了重载。并且支持类似numpy的广播特性。

In [1]:
import torch
import numpy as np

In [2]:
a = torch.tensor([[1.0, 2], [-3, 4.0]])
b = torch.tensor([[5.0, 6], [7.0, 8.0]])
a + b  # 运算符重载

tensor([[ 6.,  8.],
        [ 4., 12.]])

In [3]:
a - b

tensor([[ -4.,  -4.],
        [-10.,  -4.]])

In [4]:
a * b

tensor([[  5.,  12.],
        [-21.,  32.]])

In [5]:
a / b

tensor([[ 0.2000,  0.3333],
        [-0.4286,  0.5000]])

In [6]:
a ** 2

tensor([[ 1.,  4.],
        [ 9., 16.]])

In [7]:
a ** (0.5)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [8]:
# 求模

a % 3 

tensor([[1., 2.],
        [0., 1.]])

In [9]:
# 向下取整出（地板除）
a // 3  

tensor([[ 0.,  0.],
        [-1.,  1.]])

In [10]:
a >= 2 # torch.ge(a, 2)  #ge: greater_equal缩写

tensor([[False,  True],
        [False,  True]])

In [11]:
(a >= 2) & (a <= 3)

tensor([[False,  True],
        [False, False]])

In [12]:
(a >= 2) | (a <= 3)


tensor([[True, True],
        [True, True]])

In [13]:
a == 5 # torch.eq(a, 5)

tensor([[False, False],
        [False, False]])

In [14]:
torch.sqrt(a)

tensor([[1.0000, 1.4142],
        [   nan, 2.0000]])

In [15]:
a = torch.tensor([1.0, 8.0])
b = torch.tensor([5.0, 6.0])
c = torch.tensor([6.0, 7.0])

d = a + b + c
print(d)

tensor([12., 21.])


In [16]:
print(torch.max(a, b))

tensor([5., 8.])


In [17]:
print(torch.min(a, b))

tensor([1., 6.])


In [18]:
x = torch.tensor([2.6, -2.7])

print(torch.round(x)) # 保留整数部分，四舍五入
print(torch.floor(x)) # 保留整数部分，向下归整
print(torch.ceil(x))  # 保留整数部分，向上归整
print(torch.trunc(x)) # 保留整数部分，向0归整

tensor([ 3., -3.])
tensor([ 2., -3.])
tensor([ 3., -2.])
tensor([ 2., -2.])


In [19]:
x = torch.tensor([2.6, -2.7])
print(torch.fmod(x, 2)) # 作除法取余数 
print(torch.remainder(x, 2)) #作除法取剩余的部分，结果恒正

tensor([ 0.6000, -0.7000])
tensor([0.6000, 1.3000])


In [20]:
# 幅值裁剪

x = torch.tensor([0.9, -0.8, 100.0, -20.0, 0.7])
y = torch.clamp(x, min = -1, max = 1)
z = torch.clamp(x, max = 1)
print(y)
print(z)

tensor([ 0.9000, -0.8000,  1.0000, -1.0000,  0.7000])
tensor([  0.9000,  -0.8000,   1.0000, -20.0000,   0.7000])


## 二、向量运算
向量运算符只在一个特定轴上运算，将一个向量映射到一个标量或者另外一个向量。

In [21]:
#统计值

a = torch.arange(1, 10).float()
print(a)
print(torch.sum(a))
print(torch.mean(a))
print(torch.max(a))
print(torch.min(a))
print(torch.prod(a)) # 累乘
print(torch.std(a))  # 标准差
print(torch.var(a))  # 方差
print(torch.median(a)) # 中位数

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor(45.)
tensor(5.)
tensor(9.)
tensor(1.)
tensor(362880.)
tensor(2.7386)
tensor(7.5000)
tensor(5.)


In [22]:
# std

a = torch.arange(1, 10).float()
b = torch.zeros_like(a, dtype = torch.float) # 必须先初始化b
b = torch.fill_(b, torch.mean(a))
c = (a - b) ** 2
std = torch.sqrt((torch.sum(c) / (len(a) - 1))) # 样本标准差除以n-1 总体标准差除以n
print(std)

tensor(2.7386)


In [23]:
#指定维度计算统计值

b = a.view(3, 3)
print(b)
print(torch.max(b, dim = 0))
print(torch.max(b, dim = 1))

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.return_types.max(
values=tensor([7., 8., 9.]),
indices=tensor([2, 2, 2]))
torch.return_types.max(
values=tensor([3., 6., 9.]),
indices=tensor([2, 2, 2]))


In [24]:
# cum

a = torch.arange(1, 10)
print(a)
print(torch.cumsum(a, 0))
print(torch.cumprod(a, 0))

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  3,  6, 10, 15, 21, 28, 36, 45])
tensor([     1,      2,      6,     24,    120,    720,   5040,  40320, 362880])


In [25]:
# torch.sort和torch.topk可以对张量排序

# torch.topk(input, k, dim=None, largest=True, sorted=True, *, out=None) -> (Tensor, LongTensor)
# Returns the k largest elements of the given input tensor along a given dimension.
# If largest is False then the k smallest elements are returned.

a = torch.tensor([[9, 7, 8], [1, 3, 2], [5, 6, 4]]).float()
print(a, "\n")
print(torch.topk(a, 2, dim = 0), "\n") # 对dim1操作
print(torch.topk(a, 2, dim = 1), "\n") # 对dim0操作
print(torch.sort(a, dim = 1), "\n") # 只有dim1可变，dim0不变 -> 对dim0排序

#利用torch.topk可以在Pytorch中实现KNN算法

tensor([[9., 7., 8.],
        [1., 3., 2.],
        [5., 6., 4.]]) 

torch.return_types.topk(
values=tensor([[9., 7., 8.],
        [5., 6., 4.]]),
indices=tensor([[0, 0, 0],
        [2, 2, 2]])) 

torch.return_types.topk(
values=tensor([[9., 8.],
        [3., 2.],
        [6., 5.]]),
indices=tensor([[0, 2],
        [1, 2],
        [1, 0]])) 

torch.return_types.sort(
values=tensor([[7., 8., 9.],
        [1., 2., 3.],
        [4., 5., 6.]]),
indices=tensor([[1, 2, 0],
        [0, 2, 1],
        [2, 0, 1]])) 



## 三、矩阵运算
矩阵必须是二维的。类似torch.tensor([1,2,3])这样的不是矩阵。

矩阵运算包括：矩阵乘法，矩阵转置，矩阵逆，矩阵求迹，矩阵范数，矩阵行列式，矩阵求特征值，矩阵分解等运算。

In [26]:
# 矩阵乘法

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[2, 0], [0, 2]])
print(a @ b)  # 等价于torch.matmul(a, b) 或 torch.mm(a, b)

tensor([[2, 4],
        [6, 8]])


In [27]:
# 矩阵转置
a = torch.tensor([[1.0, 2], [3, 4]])
print(a.t())

tensor([[1., 3.],
        [2., 4.]])


In [28]:
# 矩阵逆，必须为浮点类型

a = torch.tensor([[1.0, 2], [3, 4]])
inverse_a = torch.inverse(a)
print(a)
print(inverse_a)
print(a @ inverse_a) # 结果是对的 = E

tensor([[1., 2.],
        [3., 4.]])
tensor([[-2.0000,  1.0000],
        [ 1.5000, -0.5000]])
tensor([[ 1.0000e+00,  0.0000e+00],
        [-4.7684e-07,  1.0000e+00]])


In [29]:
# 矩阵求迹(trace, 主对角线各元素之和) 

a = torch.tensor([[1.0, 2], [3, 4]])
print(torch.trace(a))

tensor(5.)


In [30]:
# 矩阵求范数

a = torch.tensor([[1.0, 2], [3, 4]])
print(torch.norm(a)) # 默认求2范数
print(torch.norm(a, p = 1)) # 求1范数

tensor(5.4772)
tensor(10.)


In [31]:
# 矩阵行列式
a = torch.tensor([[1.0, 2], [3, 4]])
print(torch.det(a))

tensor(-2.0000)


In [32]:
# 矩阵特征值和特征向量
a = torch.tensor([[1.0, 2], [-5, 4]], dtype = torch.float)
print(torch.eig(a, eigenvectors=True))

#两个特征值分别是 -2.5+2.7839j, 2.5-2.7839j 


torch.return_types.eig(
eigenvalues=tensor([[ 2.5000,  2.7839],
        [ 2.5000, -2.7839]]),
eigenvectors=tensor([[ 0.2535, -0.4706],
        [ 0.8452,  0.0000]]))


In [33]:
# 矩阵QR分解, 将一个方阵分解为一个正交矩阵q和上三角矩阵r
# QR分解实际上是对矩阵a实施Schmidt正交化得到q

a  = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
q, r = torch.qr(a)
print(q, "\n")
print(r, "\n")
print(q @ r)

tensor([[-0.3162, -0.9487],
        [-0.9487,  0.3162]]) 

tensor([[-3.1623, -4.4272],
        [ 0.0000, -0.6325]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000]])


In [34]:
# 矩阵svd分解
# svd分解可以将任意一个矩阵分解为一个正交矩阵u,一个对角阵s和一个正交矩阵v.t()的乘积
# svd常用于矩阵压缩和降维

a=torch.tensor([[1.0, 2.0], [3.0, 4.0], [5.0, 6.0]])

u, s, v = torch.svd(a)

print(u, "\n")
print(s, "\n")
print(v, "\n")

print(u @ torch.diag(s) @ v.t())

#利用svd分解可以在Pytorch中实现主成分分析降维

tensor([[-0.2298,  0.8835],
        [-0.5247,  0.2408],
        [-0.8196, -0.4019]]) 

tensor([9.5255, 0.5143]) 

tensor([[-0.6196, -0.7849],
        [-0.7849,  0.6196]]) 

tensor([[1.0000, 2.0000],
        [3.0000, 4.0000],
        [5.0000, 6.0000]])


## 四、广播机制
Pytorch的广播规则和numpy是一样的:

1、如果张量的维度不同，将维度较小的张量进行扩展，直到两个张量的维度都一样。 <p>
2、如果两个张量在某个维度上的长度是相同的，或者其中一个张量在该维度上的长度为1，那么我们就说这两个张量在该维度上是相容的。<p>
3、如果两个张量在所有维度上都是相容的，它们就能使用广播。<p>
4、广播之后，每个维度的长度将取两个张量在该维度长度的较大值。<p>
5、在任何一个维度上，如果一个张量的长度为1，另一个张量长度大于1，那么在该维度上，就好像是对第一个张量进行了复制。<p>
torch.broadcast_tensors可以将多个张量根据广播规则转换成相同的维度。<p>

In [35]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([[0, 0, 0], [1, 1, 1], [2, 2, 2]])
print(b + a) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


In [36]:
a_broad, b_broad = torch.broadcast_tensors(a, b)
print(a_broad, "\n")
print(b_broad, "\n")
print(a_broad + b_broad) 

tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]) 

tensor([[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]]) 

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])
